### ISSUE TITLE
Handle length-difference-of-one case

### ISSUE THREAD

**Issue by rreusser** [jarofghosts/interleave-array#1]
I was trying to use this as a sort of join, e.g.:

``` javascript
interleaveArray([1, 2], [3])
// => [1, 3, 2]
```

Maybe this isn't how it's intended to function, but was just curious what you think about a PR to handle this case since it seems that off-by-one lengths can still be meaningfully interleaved. Thanks!

**Comment by jarofghosts** [comment]
Yeah, this was modeled directly after [clojure's `interleave` function](https://clojuredocs.org/clojure.core/interleave). This behavior should definitely be documented, though; sorry about that!

To me, that behavior is different enough to warrant a separate module, which I might write if I have time today.

**Comment by rreusser** [comment]
Cool, makes sense. Yeah, figured was maybe just a slightly different use case or set of requirements that the name didn't fully capture (there are [limits to verbosity](https://www.npmjs.com/package/ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou), of course). Here's what I have for a one-minute just-make-it-work solution:

``` javascript
'use strict'

export default function interleaveArrays(a, b) {
  var result = []
  var aLength = a.length
  var bLength = b.length
  var n = Math.max(aLength, bLength)
  for (var i = 0; i < n; i++) {
    if (i < aLength) {
      result.push(a[i])
    }
    if (i < bLength) {
      result.push(b[i])
    }   
  }
  return result
}
```

Could definitely be optimized, but it's… a thing that has its place at least.

**Comment by jarofghosts** [comment]
here, i made [a thing](https://github.com/jarofghosts/loose-interleave) and also [updated the readme for this module](https://github.com/jarofghosts/interleave-array/commit/dfd37083808ac9eb90aeaedb8977a02e4a8319f0). thanks for bringing this up!

**Comment by rreusser** [comment]
Nice! Thanks so much. I see now that it handles more than two arguments. Need to go at the moment, but I might submit a quick PR to document just a couple more corner cases for these modules. This looks great though. Your responsiveness is greatly appreciated!

**Comment by jarofghosts** [comment]
that would be great if you have the time, thanks!
